### PR TITLE
upgrade flask to 3.x

### PR DESCRIPTION
**Pull request by asottile-sentry**
failing on:

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
```

### CODE REVIEW

**Review by realkosty — APPROVED** [review]
Tested by merging all 5 outstanding PR branches together, running ./deploy_tda.sh and verifying events continue to stream into demo org. Means this still works with `python3.8` which is what we are using (for a reason that eludes me, maybe something specific to GCP).
